# Generated by Django 3.2 on 2022-09-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.IntegerField(default=0)),
                ('title', models.CharField(default='', max_length=100)),
                ('rating', models.URLField()),
            ],
        ),
    ]
