# Generated by Django 3.2 on 2022-09-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='rating',
            field=models.CharField(default='', max_length=100),
        ),
    ]
