# Generated by Django 3.2 on 2022-09-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20220915_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_id', models.IntegerField(default=0)),
                ('title', models.CharField(default='', max_length=100)),
                ('rating', models.CharField(default='', max_length=100)),
                ('content', models.TextField(default='', max_length=5000)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RenameField(
            model_name='video',
            old_name='video_id',
            new_name='v_id',
        ),
    ]
