# Generated by Django 3.2 on 2022-09-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.IntegerField(default=0)),
                ('title', models.CharField(default='', max_length=100)),
                ('location', models.CharField(default='', max_length=100)),
                ('price', models.CharField(default='', max_length=10)),
                ('rating', models.CharField(default='', max_length=20)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
