# Generated by Django 3.2 on 2022-10-15 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='h_id',
            new_name='hotel_id',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='title',
            new_name='hotel_title',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='p_id',
            new_name='place_id',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='title',
            new_name='place_title',
        ),
    ]
