# Generated by Django 3.2 on 2022-10-16 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_auto_20221016_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_desc3',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_desc4',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_desc5',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_desc6',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_image3',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_image4',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_image5',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_image6',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_price3',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_price4',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_price5',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_price6',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_rating3',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_rating4',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_rating5',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_rating6',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_title3',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_title4',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_title5',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_title6',
        ),
    ]
