# Generated by Django 3.2 on 2022-10-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_auto_20221016_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='cleanliness',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='hotel',
            name='comfort',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='hotel',
            name='facilities',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='hotel',
            name='reviews',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='hotel',
            name='value_for_money',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
