# Generated by Django 3.2 on 2023-12-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_auto_20221016_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image_url',
            field=models.URLField(default=''),
        ),
    ]
